### ISSUE TITLE
Templates not found

### ISSUE THREAD

**Issue by akhayyat** [simahawk/openerp_bootstrap#2]
Running `paster create -t openerp_newmodule`, after answering all the prompts, I get the following:

``` python
Creating template openerp_newmodule
Traceback (most recent call last):
  File "~/.virtualenvs/erp/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/command.py", lin
e 104, in run
    invoke(command, command_name, options, args[1:])
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/command.py", lin
e 143, in invoke
    exit_code = runner.run(args)
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/command.py", lin
e 238, in run
    result = self.command()
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/create_distro.py", line 137, in command
    template, output_dir, vars)
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/create_distro.py", line 196, in create_template
    template.run(self, output_dir, vars)
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/templates.py", line 58, in run
    self.write_files(command, output_dir, vars)
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/templates.py", line 127, in write_files
    template_renderer=self.template_renderer)
  File "~/.virtualenvs/erp/local/lib/python2.7/site-packages/paste/script/copydir.py", line 71, in copy_dir
    names = os.listdir(source)
OSError: [Errno 2] No such file or directory: '~/.virtualenvs/erp/local/lib/python2.7/site-packages/openerp_bootstrap/templates/newmodule'
```

Indeed, there is no `templates` folder.

**Comment by cedricbonhomme** [comment]
Same problem here after having installed the version 1.0b3.
It arrives just after the prompt:
"
Enter is_web (Is web addon? [yes/no]) ['no']:
"

**Comment by lazywhite** [comment]
same error here
